#!/usr/bin/perl

sub setup {        
	# ensure all interfaces use an address
	for (my $i = 1; $i <= 8; $i++) {	
		`/sbin/ifconfig eth$i 192.168.$i.1`;
	}

	# verify kernel module not loaded
        
	my $of_kmod_loaded = `lsmod | grep openflow_mod`;        
	if ($of_kmod_loaded eq "") {                
		print "loading kernel module\n";        
	}
        else {                
		print "openflow kernel module already loaded... please fix!\n";
		exit 1;
        }        
	
	# verify controller not already running
        my $controller_loaded = `ps -A | grep controller`;        
	if ($controller_loaded eq "") 
	{
                # controller not loaded, good
        }        
	else {                
		print "controller already loaded... please remove and try again!\n";
                exit 1;
        }

	my $openflow_dir=$ENV{OF_ROOT};

        # create openflow switch on four ports
        `insmod ${openflow_dir}/datapath/linux-2.6/openflow_mod.ko`;
        `dpctl adddp 0`;
        `dpctl addif 0 eth1`;
        `dpctl addif 0 eth2`;
        `dpctl addif 0 eth3`;
        `dpctl addif 0 eth4`;
}

setup();

exit(0);

